"use client";

import { ChangeEvent, useState } from "react";
import Link from "next/link";
import { arrayBufferToBase64, encryptFile } from "@/lib/crypto";

export default function TransferClient() {
  const [files, setFiles] = useState<File[]>([]); const [password, setPassword] = useState(""); const [authRequired, setAuthRequired] = useState(false); const [maxDownloads, setMaxDownloads] = useState("0"); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [link, setLink] = useState("");
  const select = (event: ChangeEvent<HTMLInputElement>) => { setFiles(Array.from(event.target.files || []).slice(0, 10)); setLink(""); };
  async function upload() {
    if (!files.length) return setError("Choose at least one file."); if (password.length < 8) return setError("Use a transfer password of at least 8 characters."); if (files.some(file => file.size > 50 * 1024 * 1024)) return setError("Each file must be 50 MB or smaller."); setLoading(true); setError("");
    try { const form = new FormData(); form.set("maxDownloads", maxDownloads || "0"); form.set("allowSave", "true"); form.set("authRequired", String(authRequired)); for (const file of files) { const encrypted = await encryptFile(file, password); form.append("files", new File([encrypted.encryptedData], `${file.name}.zyphor`, { type: "application/octet-stream" })); form.append("salt", arrayBufferToBase64(encrypted.salt)); form.append("iv", arrayBufferToBase64(encrypted.iv)); form.append("originalName", file.name); form.append("originalMime", file.type || "application/octet-stream"); } const response = await fetch("/api/upload", { method: "POST", body: form }); const data = await response.json(); if (!response.ok || !data?.success) throw new Error(data?.error || "Upload failed."); setLink(`${window.location.origin}/${data.linkId}#${encodeURIComponent(password)}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Upload failed."); } finally { setLoading(false); }
  }
  return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 24 }}><section className="glass-panel" style={{ width: "100%", maxWidth: 720 }}><h1 className="title-gradient" style={{ textAlign: "center", fontSize: "2.3rem" }}>Zyphor Files</h1><p style={{ textAlign: "center", color: "var(--text-secondary)" }}>Encrypt files locally, then share one secure link.</p>{error && <p style={{ color: "#ff5555" }}>{error}</p>}{link ? <div style={{ display: "grid", gap: 12 }}><p style={{ color: "#10b981" }}>Transfer ready. The password is in the link fragment and is not sent to Zyphor.</p><input className="input-field" readOnly value={link} /><button className="btn btn-primary" onClick={() => navigator.clipboard.writeText(link)}>Copy secure link</button><button className="btn btn-secondary" onClick={() => { setFiles([]); setPassword(""); setLink(""); }}>Create another transfer</button></div> : <div style={{ display: "grid", gap: 16 }}><input type="file" multiple onChange={select} /><p style={{ color: "var(--text-secondary)", margin: 0 }}>{files.length ? files.map(file => file.name).join(", ") : "Up to 10 files, 50 MB each."}</p><input className="input-field" type="password" value={password} onChange={event => setPassword(event.target.value)} placeholder="Transfer password (kept on your device)" /><label style={{ color: "var(--text-secondary)" }}>Maximum downloads (0 = unlimited)<input className="input-field" type="number" min="0" max="1000" value={maxDownloads} onChange={event => setMaxDownloads(event.target.value)} /></label><label><input type="checkbox" checked={authRequired} onChange={event => setAuthRequired(event.target.checked)} /> Require Zyphor sign-in to download</label><button className="btn btn-primary" disabled={loading} onClick={upload}>{loading ? "Encrypting and uploading…" : "Encrypt and share"}</button><p style={{ textAlign: "center", color: "var(--text-secondary)", margin: 0 }}>Need an account? <Link href="/login">Sign in</Link></p></div>}</section></main>;
}
